"""Verify contact assembly on saved geometry and displacement before equilibrium use."""
import argparse,json
from pathlib import Path
import numpy as np,meshio
from skfem.io import from_meshio
from clipped_sole_assembly import prepare,assemble
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--out',type=Path,required=True);a=p.parse_args();a.out.mkdir(parents=True,exist_ok=False)
plan={'scope':__doc__,'relative_directional_tangent_error_max':1e-5,'force_integral_difference_N_max':1e-7,'finite_difference_step_mm':1e-8,'seed':2301};(a.out/'plan.json').write_text(json.dumps(plan,indent=2)+'\n')
root=Path('validation/sole_extended_contact_mesh_v1');meshes=[from_meshio(meshio.read(root/n/f'{n}_0.5.msh')) for n in ['boss','spacer']];patches,n,prep=prepare(*meshes);u=np.load('validation/sole_projected_contact_probe_v1/fields.npz')['u_mm'];f,K,r=assemble(patches,n,u);d=np.random.default_rng(plan['seed']).normal(size=n);d/=np.max(abs(d));eps=plan['finite_difference_step_mm'];fp,_,_=assemble(patches,n,u+eps*d);fm,_,_=assemble(patches,n,u-eps*d);fd=(fp-fm)/(2*eps);exact=-K@d;err=float(np.linalg.norm(fd-exact)/np.linalg.norm(exact));nb=3*meshes[0].p.shape[1];total=float(f[:nb].reshape(-1,3)[:,2].sum());old=json.loads(Path('validation/sole_contact_integration_audit_v1/report.json').read_text())['clipped_pressure_integral_N'];delta=abs(total-old);balance=float(np.linalg.norm(f.reshape(-1,3).sum(axis=0)));xyz=np.r_[meshes[0].p.T,meshes[1].p.T];moment=np.cross(xyz-[35,6,-19],f.reshape(-1,3)).sum(axis=0)
result={'preparation':prep,'relative_directional_tangent_error':err,'contact_force_N':total,'difference_from_scalar_integration_N':delta,'action_reaction_residual_N':balance,'moment_residual_Nmm':moment.tolist(),'integration':r,'gates':{'directional_tangent':err<=1e-5,'scalar_integral_agreement':delta<=1e-7,'force_balance':balance<=1e-8,'moment_balance':np.linalg.norm(moment)<=1e-8},'equilibrium_resolved':False,'joint_verified':False};result['gates']={k:bool(v) for k,v in result['gates'].items()};(a.out/'report.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2));raise SystemExit(0 if all(result['gates'].values()) else 1)
