"""Connect a default-clear open-drain interface; firmware and brownout remain unqualified."""
import copy,csv,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'schematics/power/protected_pack_system_candidate_v3';OUT.mkdir(exist_ok=True)
source=ROOT/'schematics/power/protected_pack_system_candidate_v2/assembly.json';a=json.loads(source.read_text());r=copy.deepcopy(a);p={x['reference']:x for x in r['parts']}
assert p['CTRL__U_HOST']['part']=='STM32G030F6P6' and p['CTRL__U_HOST']['pins']['11'] is None
assert p['SYS__U14']['pins']['2']=='SYS__SEQUENCE_CLEAR_REQUEST' and p['SYS__U14']['pins']['4']=='SYS__RESET_N'
assert p['SYS__R14']['pins']=={'1':'SYS__LOGIC3V3','2':'SYS__SEQUENCE_CLEAR_REQUEST'}
p['CTRL__U_HOST']['pins']['11']='CTRL_RESET_RELEASE_N'
r['parts'] += [ {'reference':'IF_CLEAR__U_OD','part':'SN74LVC1G07DBVR','pins':{'1':None,'2':'CTRL_RESET_RELEASE_N','3':'PACK_RETURN','4':'SYS__SEQUENCE_CLEAR_REQUEST','5':'CTRL3V3'},'integration_group':'sequence_clear_interface'}, {'reference':'IF_CLEAR__R_INPUT_PU','part':'TNPW060310K0BEEA','value_ohm':10000,'pins':{'1':'CTRL3V3','2':'CTRL_RESET_RELEASE_N'},'placement':'At buffer input; retain high when MCU pad is high impedance','integration_group':'sequence_clear_interface'}, {'reference':'IF_CLEAR__C_HF','part':'GRM31C5C1H104JA01L','value_F':1e-7,'pins':{'1':'CTRL3V3','2':'PACK_RETURN'},'integration_group':'sequence_clear_interface'}]
assert len(r['parts'])==194 and len({x['reference'] for x in r['parts']})==194
r['unresolved_signal_ports'].pop('SYS__SEQUENCE_CLEAR_REQUEST')
r['sequence_clear_interface']={'MCU_pin':'TSSOP20 pin11 PA4','polarity':'CTRL_RESET_RELEASE_N high -> OD open -> SYS clear request high -> SYS reset low; command low permits reset release only','normal_logic_states':[{'MCU':'high','buffer_output':'Z','SYS_clear':'high','reset_contribution':'assert low'},{'MCU':'low','buffer_output':'low','SYS_clear':'low','reset_contribution':'high impedance, other reset sources still authoritative'},{'MCU':'high impedance; CTRL supply valid','buffer_output':'Z via10k input pullup','SYS_clear':'high','reset_contribution':'assert low'},{'MCU':'CTRL supply0V; SYS valid','buffer_output':'Ioff high impedance','SYS_clear':'high subject to leakage budget','reset_contribution':'assert low subject to DC margins'}],'limits':['Polarity table is not analog timing proof','Full MCU reset pad leakage/state and power-up behavior must be verified','No brownout guarantee for0<CTRL3V3<specified operating range','Output leakage, SYS1k pullup, input capacitance/edge rate and reset fanout margins need closure','New CTRL pullup/static/dynamic current and100nF need budget update','Firmware must default to clear and only permit release after startup qualification; firmware implementation outside this goal'],'sources':[{'url':'https://www.ti.com/lit/ds/symlink/sn74lvc1g07.pdf','revision':'AG October2025','sections':['4 DBV pinout','7.4 truth table','7.1 Ioff']},{'url':'https://www.st.com/resource/en/datasheet/stm32g030f6.pdf','revision':'DS12991 Rev6','section':'Table12 TSSOP20 pin11 PA4'}],'qualified':False}
r['status']='sequence_clear_driver_connected_candidate_not_operational';r['remaining']=[x for x in r['remaining'] if x!='Both regulator allow drivers and reset sequencing'];r['remaining'].append('Both regulator allow drivers, sequence clear analog and firmware contract qualification')
r['source_sha256']={str(source.relative_to(ROOT)):hashlib.sha256(source.read_bytes()).hexdigest()};r['checks']['sequence_clear_pin11_unused_before_assignment']=True
r['checks'].pop('unique191references',None);r['checks']['unique194references']=True
(OUT/'assembly.json').write_text(json.dumps(r,indent=2)+'\n')
for filename,header,rows in [('bom.csv',['reference','part','group'],[[x['reference'],x.get('part'),x.get('integration_group')] for x in r['parts']]),('connections.csv',['reference','pin','net'],[[x['reference'],pin,net] for x in r['parts'] for pin,net in x['pins'].items()])]:
 with (OUT/filename).open('w',newline='') as f:w=csv.writer(f,lineterminator='\n');w.writerow(header);w.writerows(rows)
print(json.dumps({'references':194,'remaining_open_signal_nets':list(r['unresolved_signal_ports']),'firmware_implemented':False,'qualified':False}))
